- name: this playbook will create the vpc in aws
  hosts: localhost
  become: true
  connection: local
  gather_facts: false
  tasks:
    - name: import vpc variable
      include_vars: vars/vpc_setup

    - name: create vpc profile
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default